name: medhive
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1
  firebase_auth: ^4.19.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  flutter_credit_card: ^4.0.1
  flutter_fadein: ^2.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/mh_app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/mh_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
